// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unccvnegwvgkcdackvaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuY2N2bmVnd3Zna2NkYWNrdmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NDQxMDYsImV4cCI6MjA1MjUyMDEwNn0.s65bJofI_NTLUxtz70qBV16cdiQl-OXwv-io3DqWa9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);